Implement Oracle 11g guest image build scripts
This commit contain new scripts needed for building Oracle 11g RHEL 7
guest images.

Some base RHEL elements has also been changed to avoid issues when
building Oracle 11g images:

1) rhel-guest/install.d/15-reddwarf-dep:

Removed redundant pip install instructions, which caused sporatic
errors when kick-starting with DIB_NO_TMPFS=1.

The code being removed installed pip 1.5.6 on top of 6.1.1, and
then upgrade back to 6.1.1. pip 6.1.1 has different folder
structures, and downgrading back to 1.5.6 broke the reference to
the req module, causing pip to crash with an error like this:
@six.wraps(f)
AttributeError: 'module' object has no attribute 'wraps'

2) trove-guest.systemd.conf:

Removed PrivateTmp=true from the troveguest service config file.
Oracle needs to see the mount point of the Cinder volume at the
root namespace (i.e. /proc/mounts). Setting PrivateTmp to true
makes the mount point only visible from within the troveguest process's
namespace (i.e. /proc/[PID]/mounts), rendering the Oracle database
unusable.

3) rhel-guest/pre-install.d

Remove firewalld from the base RHEL installation. secrules are managed
through OpenStack. The other images also don't have firewall service
installed.

Change-Id: Ibccce0652998270e9ef9788002a13c0e3098389f
Implements: DBAAS-415